### PR TITLE
Pass the placeholder to the view

### PR DESCRIPTION
**Pull request by aerni**
This PR implements issue #37. You have now access to the placeholder of the default image in the view.

### CODE REVIEW

**Comment by riasvdv** [comment]
You already receive the full `$sources` array inside the view though, is that not enough?

**Comment by aerni** [comment]
The `$sources` array doesn't contain the `placeholder` though.

**Comment by riasvdv** [comment]
But you're taking it from the `$sources` here https://github.com/spatie/statamic-responsive-images/pull/38/files#diff-d2acad4554943fe7da3f5d001901edf4888fb89105fea10376df58684c1f222cR69

It's the same variable as passed here https://github.com/spatie/statamic-responsive-images/pull/38/files#diff-d2acad4554943fe7da3f5d001901edf4888fb89105fea10376df58684c1f222cR71

**Comment by aerni** [comment]
Ah, I see what you mean. I thought you were saying, that the `placeholder` was already part of the `sources` array before this PR. Which isn't the case.

I'm passing the `placeholder` separately because you can't do stuff like `$sources->last()['placeholder']` in Antlers. And I'm sure there are people that publish the view, change stuff, and prefer Antlers instead of Blade. Including me 😉

**Comment by riasvdv** [comment]
Thanks!

**Pull request merged**
