### PR TITLE
Return empty string when image is not found

### PR DESCRIPTION
**Pull request by kevinmeijer97**
Statamic pages result in a 404 when an image is not found. Returning an empty string here avoids this issue.

### CODE REVIEW

**Comment by ncla** [comment]
Does this fix issue #241?

**Comment by ncla** [comment]
Hmm I see it is similar, but not exact one. Seems like Glide exception handling has changed since last time I worked with Statamic.

**Comment by ncla** [comment]
I can't reproduce the 404. I changed asset field value to a non existing file, but the responsive tag just rendered nothing - which is to be expected. Can you please provide reproduction steps?

**Comment by kevinmeijer97** [comment]
What made it breaking for us was as followed:
We had a testing and production environment, we pulled the production DB to the testing environment but didn't sync the assets.
This made it so that there was an image set on an image field, during render it would search for this asset but couldn't find it since we hadn't synced the assets. 
After this it would throw the 404 on our missing asset and our page as a whole.
I was able to reproduce this on multiple sites that we maintain by doing the steps above.

**Comment by riasvdv** [comment]
Thanks!

**Pull request merged**
